import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import styled from "styled-components";
import Header from "@/components/Layout/header";
import { useRecoilState, useRecoilValue } from "recoil";
import { counterState } from "@/recoil/atoms/counterAtom";
import Link from "next/link";
import { useQuery } from "react-query";

const inter = Inter({ subsets: ["latin"] });

const Box = styled.div`
  border: 2px solid white;
  width: 200px;
  :hover {
    background-color: red;
    cursor: pointer;
  }
`;

export default function Home() {
  const count = useRecoilValue(counterState);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex flex-col">
        <Link href="/test/tailwind">tailwind</Link>
        <Link href="/test/recoil">recoil</Link>
        <Link href="/test/react_query">react query</Link>
      </div>
      <div>currentCount : {count}</div>

      <Box>Hello</Box>
    </>
  );
}
